### ISSUE TITLE
cho e hỏi lỗi bản 2.10 trên angualar 16

### ISSUE THREAD

**Issue by khanhtungmtp** [id1945/ngx-print-element#10]
e bị lỗi css này thì fix thế nào vậy a  https://drive.google.com/file/d/17tQwT4-KcZommLb0DBayBkKixMIjT6Wy/view

**Comment by khanhtungmtp** [comment]
e mới setup project angular 16 từ đầu và  @import '~ngx-print-element/styles.css'; thì bị lỗi

**Comment by id1945** [comment]
@khanhtungmtp Import css vào trong angular.json

```javascript
"styles": [
       "src/styles.scss",
       "node_modules/ngx-print-element/styles.css"
],
```
