### ISSUE TITLE
Sự kiện cancel print

### ISSUE THREAD

**Issue by khanhtungmtp** [id1945/ngx-print-element#13]
A cho e hỏi có cách nào để bắt được sự kiện khi người ta bấm nút cancel ko vậy nhỉ, case e là đếm số lần họ print lại, 
e thấy bấm cancel hay bấm print nó đều chạy,

**Comment by id1945** [comment]
@khanhtungmtp Đã fix v2.1.1. Update đi nhé bạn. Ở bản này sự thay đổi khá nhiều.

**Comment by khanhtungmtp** [comment]
ok ad để e cài thử, mà bắt đc sự kiện cancel ko hả anh

**Comment by id1945** [comment]
@khanhtungmtp Chỉ có sự kiện afterprint thôi.
Update lại version nhé bạn
v2.1.3 -> anuglar6 > angular15
v2.1.4 -> angular16

**Comment by khanhtungmtp** [comment]
sao e thấy ko có gì mới nhỉ

**Comment by id1945** [comment]
v2.1.3 v2.1.4 fix lỗi close khi print default ở v2.1.1 
Những thứ mới.
1 - Không cần import file css
2 - Sử dụng ref thay thì thẻ id
3 - Print default đã fix lỗi không nhận scss
4 - Print iframe, window.open đã cải thiện phần response

**Comment by khanhtungmtp** [comment]
Ok a
