### ISSUE TITLE
No support for Angular 18

### ISSUE THREAD

**Issue by mrazvanalex** [id1945/ngx-print-element#17]
Currently the package has no support for Angular 18. 

Will there be any support added for new angular versions?

Thanks!

**Comment by id1945** [comment]
@mrazvanalex I will update as soon as possible

**Comment by jwp1-mokid** [comment]
Currently the package has no support for Angular 17 also.

Any update?

Thanks in advance!

**Comment by id1945** [comment]
@jwp1-mokid Updated done!
