### ISSUE TITLE
Ivy support

### ISSUE THREAD

**Issue by vzakharov-rxnt** [id1945/ngx-print-element#2]
When building, getting this warning:
> Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries: - ngx-print-element [es2015/esm2015] (git+ssh://git@github.com/id1945/ngx-print-element.git) Encourage the library authors to publish an Ivy distribution.

Please add support for Ivy. Thanks!

**Comment by id1945** [comment]
Thank you for your interest in this library.
I will try to update it to a new version that supports Angular 9 Ivy as soon as possible!
Probably will be a test run version 2.0.14-rc.x

**Comment by id1945** [comment]
> When building, getting this warning:
> 
> > Generating browser application bundles (phase: setup)...Processing legacy "View Engine" libraries: - ngx-print-element [es2015/esm2015] (git+ssh://git@github.com/id1945/ngx-print-element.git) Encourage the library authors to publish an Ivy distribution.
> 
> Please add support for Ivy. Thanks!

I published version 2.0.14-rc.1
You can test it now.
