### ISSUE TITLE
không dùng được sự kiện  HostListener window afterprint 

### ISSUE THREAD

**Issue by khanhtungmtp** [id1945/ngx-print-element#7]
em có gọi services có { printMode: 'template' }
ví dụ:  this.printService.print('wrap-print', { printMode: 'template' });
khi dùng { printMode: 'template' } thì thằng sự kiện này nó không chạy  @HostListener('window:afterprint', [])
  onWindowAfterPrint() {
    console.log('ok');
} 
cho em hỏi làm sao để sử dụng được sự kiện vậy ạ, bỏ printMode đi thì chạy bình thường

**Comment by id1945** [comment]
@khanhtungmtp Upgrate lên version mới nhé!

**Comment by khanhtungmtp** [comment]
sao e thử nó vẫn ko log ra đc chữ ok nhỉ, em có xài hàm onPrint3(id: string) {
    this.print
      .print(id, { ...this.config, printMode: 'template' })
      .subscribe(console.log);
  }

  @HostListener('window:afterprint')
  onAfterPrint() {
    console.log('ok');
  }

**Comment by id1945** [comment]
@khanhtungmtp Bỏ dùng HostListener

```typescript
@HostListener('window:afterprint')
onAfterPrint() {
     console.log('ok');
}
```

Và dùng như sau

```typescript
this.print.print(id, { ...this.config, printMode: 'template' }).subscribe((event) => {
      // To do something!
     console.log(event);
});
```

**Comment by khanhtungmtp** [comment]
bản angular 16 ko hỗ trợ, a có tính update ko

**Comment by id1945** [comment]
@khanhtungmtp Có update lên 16 đó. Nếu bug này done thì mình sẽ cho bản 16 lên

**Comment by khanhtungmtp** [comment]
case e thì vẫn cần dùng @HostListener, mà sao dùng print mode thì ko dùng đc @HostListener thế a

**Comment by id1945** [comment]
@khanhtungmtp vì case đó sử dụng print trên iframe nên nó không thuộc windows hiện tại sẽ không có event afterprint
